
package org.nemanjamarjanovic.rekomendator.bussines.actor.boundary;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ActorService", targetNamespace = "http://boundary.actor.bussines.rekomendator.nemanjamarjanovic.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ActorService {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "search", targetNamespace = "http://boundary.actor.bussines.rekomendator.nemanjamarjanovic.org/", className = "org.nemanjamarjanovic.rekomendator.bussines.actor.boundary.Search")
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "http://boundary.actor.bussines.rekomendator.nemanjamarjanovic.org/", className = "org.nemanjamarjanovic.rekomendator.bussines.actor.boundary.SearchResponse")
    public String search(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param name
     */
    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://boundary.actor.bussines.rekomendator.nemanjamarjanovic.org/", className = "org.nemanjamarjanovic.rekomendator.bussines.actor.boundary.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://boundary.actor.bussines.rekomendator.nemanjamarjanovic.org/", className = "org.nemanjamarjanovic.rekomendator.bussines.actor.boundary.AddResponse")
    public void add(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
