
package org.nemanjamarjanovic.rekomendator.bussines.actor.boundary;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ActorService", targetNamespace = "http://boundary.actor.bussines.rekomendator.nemanjamarjanovic.org/", wsdlLocation = "http://localhost:8080/rekomendator-actor/webservices/ActorService?wsdl")
public class ActorService_Service
    extends Service
{

    private final static URL ACTORSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACTORSERVICE_EXCEPTION;
    private final static QName ACTORSERVICE_QNAME = new QName("http://boundary.actor.bussines.rekomendator.nemanjamarjanovic.org/", "ActorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/rekomendator-actor/webservices/ActorService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACTORSERVICE_WSDL_LOCATION = url;
        ACTORSERVICE_EXCEPTION = e;
    }

    public ActorService_Service() {
        super(__getWsdlLocation(), ACTORSERVICE_QNAME);
    }

    public ActorService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACTORSERVICE_QNAME, features);
    }

    public ActorService_Service(URL wsdlLocation) {
        super(wsdlLocation, ACTORSERVICE_QNAME);
    }

    public ActorService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACTORSERVICE_QNAME, features);
    }

    public ActorService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ActorService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ActorService
     */
    @WebEndpoint(name = "ActorServicePort")
    public ActorService getActorServicePort() {
        return super.getPort(new QName("http://boundary.actor.bussines.rekomendator.nemanjamarjanovic.org/", "ActorServicePort"), ActorService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ActorService
     */
    @WebEndpoint(name = "ActorServicePort")
    public ActorService getActorServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://boundary.actor.bussines.rekomendator.nemanjamarjanovic.org/", "ActorServicePort"), ActorService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACTORSERVICE_EXCEPTION!= null) {
            throw ACTORSERVICE_EXCEPTION;
        }
        return ACTORSERVICE_WSDL_LOCATION;
    }

}
